Argie loadingscreen enhancement
MorsHs/swine_care pull request #10
Opened 2024-11-28 03:39 UTC by argieuwu

loadingscreen enhancement

2024-11-29 06:22 UTC, MorsHs requested changes
paki change sa pubspec.lock ang flutter _advanced_drawer

paki follow ra sa kani na installation

https://pub.dev/packages/flutter_advanced_drawer/install

2024-11-29 06:25 UTC, MorsHs requested changes
paki remove sa mga dle kailangan na package sa pubspec.yaml

Like tong hiider+drawer_menu

2024-12-03 11:42 UTC, argieuwu reviewed
done removing unnecessary code

2024-12-06 06:47 UTC, MorsHs approved these changes

2024-12-06 06:47 UTC, merged